services:
  - type: web
    name: builder-api
    env: node
    plan: free
    rootDir: apps/builder
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    autoDeploy: false
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SPEC_KIT_CMD
        value: "uvx --from git+https://github.com/github/spec-kit.git specify validate . --output text"
      - key: AUTO_FIX
        value: "1"
      - key: AUTO_FIX_MAX
        value: "2"
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        value: "spencerandtheteagues"
      - key: GITHUB_REPO
        value: "starfish-prime"
      - key: GIT_AUTHOR_NAME
        value: "Neon Builder"
      - key: GIT_AUTHOR_EMAIL
        value: "spencerandtheteagues@gmail.com"
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "4001"
    healthCheckPath: /health
  - type: web
    name: builder-web
    env: node
    plan: free
    rootDir: apps/web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: false
    envVars:
      - key: NEXT_PUBLIC_BUILDER_URL
        fromService:
          type: web
          name: builder-api
          envVarKey: RENDER_EXTERNAL_URL
