services:
  # API Service - Primary REST API
  - type: web
    name: starfish-prime-api
    runtime: docker
    dockerfilePath: ./services/api/Dockerfile
    dockerContext: ./services/api
    region: oregon
    plan: starter
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://starfish-prime-web.onrender.com,https://starfish-prime-ide.onrender.com

  # Web Service - Frontend Application
  - type: web
    name: starfish-prime-web
    runtime: docker
    dockerfilePath: ./services/web/Dockerfile
    dockerContext: ./services/web
    region: oregon
    plan: starter
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true
      - key: NEXT_PUBLIC_API_URL
        value: https://starfish-prime-api.onrender.com

  # Orchestrator Service - Workflow Management
  - type: privateweb
    name: starfish-prime-orchestrator
    runtime: docker
    dockerfilePath: ./services/orchestrator/Dockerfile
    dockerContext: ./services/orchestrator
    region: oregon
    plan: starter
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true
      - key: DATABASE_URL
        sync: false

  # Worker Service - Background Processing
  - type: worker
    name: starfish-prime-worker
    runtime: docker
    dockerfilePath: ./services/worker/Dockerfile
    dockerContext: ./services/worker
    region: oregon
    plan: starter
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true

  # Preview Manager Service - Environment Management
  - type: privateweb
    name: starfish-prime-preview
    runtime: docker
    dockerfilePath: ./services/preview-manager/Dockerfile
    dockerContext: ./services/preview-manager
    region: oregon
    plan: starter
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true

  # IDE Service - Web-based IDE
  - type: web
    name: starfish-prime-ide
    runtime: docker
    dockerfilePath: ./services/ide/Dockerfile
    dockerContext: ./services/ide
    region: oregon
    plan: starter
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromRender: true
      - key: API_URL
        value: https://starfish-prime-api.onrender.com
