
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:55678

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'one-shot-api'
          metrics_path: /metrics
          static_configs:
            - targets: ['api:4000']
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  logging:
    loglevel: info
  otlphttp:
    endpoint: http://lgtm:4318

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2, 5]
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: service.name
      - name: peer.service

service:
  extensions: [health_check, pprof]
  pipelines:
    metrics:
      receivers: [prometheus, otlp, spanmetrics]
      processors: [batch]
      exporters: [logging, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp, spanmetrics]
